### PR TITLE
Use `he` for robust HTML entity encoding/decoding

### PR DESCRIPTION
**Pull request by mathiasbynens**
_ent_ has [several open issues](https://github.com/substack/node-ent/issues/created_by/mathiasbynens?state=open) that are not present in [_he_](http://mths.be/he).

### CODE REVIEW

**Comment by Raynos** [comment]
why did `&lt;` change to `&#x3C` ?

**Comment by mathiasbynens** [comment]
_he_ encodes using hexadecimal numerical character references by default because some named character references (especially the ones that originate from MathML) are not supported in older browsers.

If you feel strongly about this I’d be happy to amend this pull request to use _he_’s [`useNamedReferences` option](https://github.com/mathiasbynens/he#usenamedreferences) (but keep in mind it might break things for older browsers).

**Comment by Matt-Esch** [comment]
Does this have backcompat issues with older browsers? Or are you saying this resolves the issue of missing named entities?

**Comment by mathiasbynens** [comment]
> Does this have backcompat issues with older browsers?

_he_’s [`useNamedReferences` option](https://github.com/mathiasbynens/he#usenamedreferences) has such issues, yes. That’s why it’s disabled by default and I’d like to keep it disabled for jsonml-stringify too. `&lt;` works everywhere, so for the example in the tests it doesn’t make a difference, but as soon but there is something like `≼` in the input it would get encoded as `&PrecedesSlantEqual;` which doesn’t work in older browsers.

**Comment by mathiasbynens** [comment]
Ping @Matt-Esch @Raynos Let me know if you’d like me to change the patch to use `useNamedReferences`.

**Comment by Raynos** [comment]
@mathiasbynens I no longer use this module, its deprecated. However this looks good.

**Comment by mathiasbynens** [comment]
Mind publishing a new version with this fix anyway?

**Comment by Raynos** [comment]
published as v1.0.1

**Pull request merged**
